data:
  raw_path: "data/processed/processed_pp_prices_clean.csv"
  processed_path: "data/processed"

features:
  target_col: "Price"         # optional (case-insensitive)
  lag_days: [1, 7, 30]
  rolling_windows: [7, 30]
  exogenous: []               # e.g. ["some_exog_col"]

models:
  save_path: "models"
  xgboost:
    n_estimators: 500
    learning_rate: 0.05
    max_depth: 3
    random_state: 42
  sarimax:
    order: [1, 1, 1]
    seasonal_order: [0, 0, 0, 0]

reports:
  plots_path: "reports/plots"
