data:
  raw_path: "data/raw/raw_data.csv"
  processed_path: "data/processed"
models:
  save_path: "models"
  xgboost:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
  sarimax:
    order: [1,1,1]
    seasonal_order: [1,1,1,12]
features:
  lag_days: [1,7,30]
  rolling_windows: [7,30,90]
  exogenous: ["crude_oil", "freight_index"]
reports:
  plots_path: "reports/plots"
